# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4357f9705c31990932737a8232cccb28df6321ad0c5563dc9992027f606f10bd545f888e4905e95f4a34b1647c40c737c5098375887d2412fb0b130cd87d1c00

test:
  secret_key_base: c3c82afde9f58bd5d7a2b42bf3b8813cea1deb932f4c789ac288637ef97f516a1074d17481dd40118282985a76bef8cdb94fcaef9dc587d5d2485a93ce8c2784

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
